name: workflow.yml
on:
  push:
    branches:
      - main

jobs:
  build-image-api:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Connexion à GHCR
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: NWB-H
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: api
          push: true
          tags: |
            ghcr.io/nwb-h/windigo-serigraphie-projet-api:latest
            ghcr.io/nwb-h/windigo-serigraphie-projet-api:${{ github.sha }}

  build-image-spa:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Connexion à GHCR
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: NWB-H
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: spa
          push: true
          tags: |
            ghcr.io/nwb-h/windigo-serigraphie-projet-spa:latest
            ghcr.io/nwb-h/windigo-serigraphie-projet-spa:${{ github.sha }}

  build-api:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          context: api
          php-version: 8.2
      - run: composer install
      
  build-spa:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          context: spa
          node-version: 22.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      
  ftptO2switch:
    needs: [ build-spa, build-api]
    runs-on: ubuntu-latest
    steps:
      - name: Deploiement continue
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          
